### ISSUE TITLE
内网环境下的邮件告警失败

### ISSUE THREAD

**Issue by supervisoredis** [n9e/mail-sender#4]
runner.cwd: /root/gopath/src/github.com/didi/nightingale
runner.hostname: **************
parse configuration file: /root/gopath/src/github.com/didi/nightingale/etc/mail-sender.yml
panic: dial tcp: lookup mail.*******.com on [::1]:53: read udp [::1]:41768->[::1]:53: read: connection refused

goroutine 1 [running]:
github.com/n9e/mail-sender/config.TestSMTP(0xc000085460, 0x1, 0x1)
        C:/Users/12396/Desktop/mail-sender-master/config/funcs.go:48 +0x685
main.main()
        C:/Users/12396/Desktop/mail-sender-master/main.go:55 +0xcb

**Comment by UlricQin** [comment]
这个报错很明显，你的机器解析不了你的邮箱域名，dns有问题

**Comment by supervisoredis** [comment]
> 这个报错很明显，你的机器解析不了你的邮箱域名，dns有问题

好的，我去配置一下DNS或者尝试IP访问
